// <auto-generated />
namespace MixupActivity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mixupv7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mixupv7));
        
        string IMigrationMetadata.Id
        {
            get { return "202005031001395_Mixup-v7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
